### ISSUE TITLE
ATV14

### ISSUE THREAD

**Issue by Roby77ita** [jamal2362/SEI804_VideoInfoOverlay#8]
Since homatics updated his box to ATV14 your wonderful app doesn't work anymore

Tried a reset and fresh install but can't activate in accessibility sei804 overlay ..(I set switch to on but return immediately to off)

Thank you

**Comment by jamal2362** [comment]
Hey,

This App is EOL.
Doesn't work anymore on ATV14 and will never be.
I have tried to get it to work, but the getprop values are missing in ATV14.
